on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        # https://github.com/neoforged/NeoGradle/issues/207
        run: ./gradlew build

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Upload intermediary
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog: ${{ steps.changelog.outputs.changes }}
          game-versions: 1.18.2
          game-version-filter: releases

          curseforge-id: 847273
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar

          version: ${{ github.ref_name }}

          loaders: |
            forge

          dependencies: |
            aggro-fix(optional)
            apotheosis(optional)
            blue-skies(optional)
            braincellapi(optional)
            callable-horses(optional)
            lendercataclysm(optional)
            citadel(optional)
            alexs-cloud-storage(optional)
            configured(optional)
            dannys-expansion(optional)
            epicfight-dual-greatsword(optional)
            epic-fight-mod(optional)
            goblins-dungeons(optional)
            epic-fight-infernal-gainer(optional)
            integrated-api(optional)
            epic-knights-armor-and-weapons(optional)
            meet-your-fight(optional)
            mutant-monsters(optional)
            roughly-enough-items(optional)
            project-mmo(optional)
            irons-spells-n-spellbooks(optional)
            revamped-phantoms(optional)
            shoulder-surfing-reloaded(optional)
            shrines-structures(optional)
            yungs-better-nether-fortresses(optional)
            bygone-nether(optional)
            untamedwilds(optional)
            unvoted-shelved(optional)
            weapons-of-miracles-epicfight(optional)
            bosses-of-mass-destruction-forge(optional)

          java: |
            17
            18

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
